Update .bin/upload

diff --git a/dot_bin/executable_upload b/dot_bin/executable_upload
--- a/dot_bin/executable_upload
+++ b/dot_bin/executable_upload
@@ -5,12 +5,15 @@ set -eo pipefail
 source ~/.config/.secrets
 source ~/.config/.variables
 
-on_error() {
-    notify-send "An error occured! ☹" "Error at $1" --category transfer.error
-    exit 1
-}
+# If not in a terminal
+if [[ ! -t 1 ]]; then
+    on_error() {
+        notify-send "An error occured! ☹" "Error at $1" --category transfer.error
+        exit 1
+    }
 
-trap 'on_error ${funcstack[1]}:$LINENO' ERR
+    trap 'on_error ${funcstack[1]}:$LINENO' ERR
+fi
 
 types=$(wl-paste --list-types)
 if [[ $types == *image* ]]; then
